options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-discord-bot:$SHORT_SHA', '.']

# Step 2: Push the image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-discord-bot:$SHORT_SHA']

# Step 3: Deploy the image to Compute Engine (optional step, see explanation below)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    gcloud compute ssh instance-1 --zone=us-central1-a --command='
      docker pull gcr.io/$PROJECT_ID/my-discord-bot:$SHORT_SHA &&
      docker stop my-discord-bot-container &&
      docker rm my-discord-bot-container &&
      docker run -d --name my-discord-bot-container gcr.io/$PROJECT_ID/my-discord-bot:$SHORT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'PROJECT_ID=$PROJECT_ID'
  - 'SHORT_SHA=$SHORT_SHA'
timeout: '1200s' # Adjust the timeout based on your needs
